# =============================================================================
# Schema: Intermediate Layer
#
# Modèles d'enrichissement: staging + seeds → colonnes ode_*
# =============================================================================

version: 2

models:
  # ===========================================================================
  # SUBVENTIONS ENRICHIES
  # ===========================================================================
  - name: int_subventions_enrichies
    description: |
      Subventions enrichies avec SIRET, direction, géoloc et thématique.
      
      Sources:
      - stg_subventions_all (base)
      - stg_associations (siret, direction, objet via JOIN)
      - seed_cache_siret_by_name (siret pour non-associations)
      - seed_cache_geo_siret (géolocalisation)
      - seed_mapping_beneficiaires (thématique par pattern)
      - seed_mapping_directions (thématique par direction)
      - seed_cache_thematique_beneficiaires (thématique LLM)
      
      Enrichissements (ode_*):
      - ode_thematique: cascade pattern → direction → llm → default
      - ode_arrondissement, ode_latitude, ode_longitude: via SIRET
      - ode_source_*: traçabilité de l'enrichissement
    columns:
      - name: annee
        description: "Année fiscale"
        tests:
          - not_null
      - name: beneficiaire_normalise
        description: "Nom normalisé pour jointures"
      - name: montant
        description: "Montant de la subvention (€)"
        tests:
          - not_null
      - name: siret
        description: "SIRET 14 chars (association ou recherche)"
      - name: direction
        description: "Direction responsable (DAC, DJS...)"
      - name: ode_thematique
        description: "Thématique classifiée (pattern/direction/llm/default)"
      - name: ode_source_thematique
        description: "Source: pattern, direction, llm, default"
      - name: ode_arrondissement
        description: "Arrondissement (1-20) si géolocalisé"
      - name: ode_latitude
        description: "Latitude GPS si géolocalisé"
      - name: ode_longitude
        description: "Longitude GPS si géolocalisé"

  # ===========================================================================
  # AP PROJETS ENRICHIS
  # ===========================================================================
  - name: int_ap_projets_enrichis
    description: |
      Projets AP enrichis avec géolocalisation et type d'équipement.
      
      Sources:
      - stg_ap_projets (base avec arrondissement_regex)
      - seed_lieux_connus (équipements parisiens)
      - seed_cache_geo_ap (résultats LLM)
      
      Enrichissements (ode_*):
      - ode_arrondissement: cascade regex → lieu_connu → llm
      - ode_adresse, ode_latitude, ode_longitude
      - ode_type_equipement: regex sur texte AP
      - ode_confiance: 1.0 (regex/lieu) ou variable (llm)
    columns:
      - name: annee
        description: "Année fiscale"
        tests:
          - not_null
      - name: ap_code
        description: "Code AP unique"
      - name: ap_texte
        description: "Description du projet"
      - name: montant
        description: "Montant mandaté (€)"
        tests:
          - not_null
      - name: ode_arrondissement
        description: "Arrondissement (1-20) si localisé"
      - name: ode_adresse
        description: "Adresse si connue"
      - name: ode_latitude
        description: "Latitude GPS"
      - name: ode_longitude
        description: "Longitude GPS"
      - name: ode_type_equipement
        description: "Type: piscine, equipement_sportif, etc."
      - name: ode_source_geo
        description: "Source: regex, lieu_connu, llm"
      - name: ode_confiance
        description: "Score de confiance (0-1)"
