version: 2

models:
  - name: int_budget_central_m57
    description: |
      Budget de la mairie centrale (Ville de Paris + Département) filtré pour M57.
      Données disponibles à partir de 2019.
    columns:
      - name: annee
        description: "Exercice comptable (>= 2019)"
        tests:
          - not_null
      - name: cle_technique
        description: "Clé unique générée par hachage"
        tests:
          - unique
          - not_null
