# Sources configuration
# Define your raw data sources here
# Documentation: https://docs.getdbt.com/docs/build/sources

version: 2

sources:
  - name: raw_paris_data
    description: "Raw Paris Open Data loaded into BigQuery"
    database: open-data-france-484717  # <-- REPLACE with your GCP project ID
    schema: raw  # The dataset where raw data is loaded
    tables:
      - name: placeholder_table
        description: "Placeholder - replace with actual source tables"
        # Add your source tables here, for example:
        # - name: velib_stations
        #   description: "Vélib' bike sharing stations in Paris"
        # - name: arbres_remarquables
        #   description: "Notable trees in Paris"
