import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
await p.goto('http://localhost:3000/daily-bread?net=3750&parts=2&c=marseille', { waitUntil: 'networkidle' });
await p.waitForTimeout(1500);
const summaries = await p.locator('details summary').allTextContents();
console.log("Summaries Marseille:");
summaries.forEach(s => console.log("  -", s.replace(/\s+/g, ' ').trim().slice(0, 100)));
await browser.close();
