import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const p = await ctx.newPage();
await p.goto('http://localhost:3000/c/nice', { waitUntil: 'networkidle', timeout: 30000 });
await p.waitForTimeout(1500);
await p.evaluate(() => window.scrollTo({ top: 3300, behavior: 'instant' }));
await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/nice-marches.png' });
await p.evaluate(() => window.scrollTo({ top: 3700, behavior: 'instant' }));
await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/nice-marches-top.png' });
await browser.close();
console.log('done');
