# Paris Public Open Data - dbt Profiles
# This file can be placed here for project-specific config,
# or in ~/.dbt/profiles.yml for global config
#
# Documentation: https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup

paris_public_open_data:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /Users/theotortorici/Documents/customer-repos/open-public-data/open-data-france-484717-68f33f082f1f.json
      project: open-data-france-484717
      dataset: paris_open_data_dev
      threads: 4
      timeout_seconds: 300
      location: EU  # Paris data - use EU region
      priority: interactive
      retries: 1

    prod:
      type: bigquery
      method: service-account
      project: open-data-france-484717
      dataset: paris_open_data_prod
      threads: 4
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      keyfile: /Users/theotortorici/Documents/customer-repos/open-public-data/open-data-france-484717-68f33f082f1f.json
